#!/bin/bash
# Go to project root
cd $(git rev-parse --show-toplevel)
echo "${BLUE}${BOLD}mypy${OFF}"
poetry run mypy tile || exit 1
echo "${BLUE}${BOLD}isort${OFF}"
poetry run isort -rc .
echo "${BLUE}${BOLD}black${OFF}"
poetry run black tile/*.py 
poetry run black tests/*.py 
poetry run black create_readme.py 
git add -u
echo "${BLUE}${BOLD}README${OFF}"
python create_readme.py
git add README.md
echo "${BLUE}${BOLD}Tests${OFF}"
poetry run python -m unittest || exit 1
echo "${GREEN}${BOLD}Done${OFF}"
exit 0
